server {
    listen 80;

    location /page1 {
        root /usr/share/nginx/html;
        index page1.html;
    }

    location /page2 {
        root /usr/share/nginx/html;
        index page2.html;
    }
}
